---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nectarine-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: transform:users
            templateRef: &template-ref
              name: nectarine-transform-template
              template: transform
            arguments:
              parameters:
              - name: target
                value: users
          - name: transform:items
            templateRef:
              <<: *template-ref
            arguments:
              parameters:
              - name: target
                value: items
        - - name: transform:interactions
            templateRef:
              <<: *template-ref
            arguments:
              parameters:
              - name: target
                value: interactions
        - - name: train
            dependencies: [transform]
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nectarine-transform-template
spec:
  entrypoint:
  templates:
    - name: transform
      container:
        image: '{{ .Values.image.uri }}:{{ .Values.image.tag }}'
        command:
          - python -m
          - nectarine.transform
        args:
          - --target {{ `{{ inputs.parameters.target }}` }}
          - --data {{ `{{ inputs.parameters.data }}` }}
          - --schema {{ `{{ inputs.parameters.schema }}` }}
        volumeMounts:
          - name: schema
            mountPath: /etc/config
      volumes:
        - name: schema
          configMap:
            name: nectarine-data-schema
