---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:
spec:
  project: default
  source:
    repoURL: https://github.com/joseprsm/nectarine.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: nectarine
