name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      registry:
        type: string
      image:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}-${{ inputs.target }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: ${{ inputs.target }}
          tags: latest
