on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: joseprsm/nectarine/.github/workflows/.test.template.yml@main
    strategy:
      matrix:
        target: [ transform, train ]
        version: [ "3.10" ]
    with:
      target: ${{ matrix.target }}
      python_version: ${{ matrix.version }}

  build:
    uses: joseprsm/nectarine/.github/workflows/.build.template.yml@main
    needs: test
    strategy:
      matrix:
        target: [transform, train]
    permissions:
      packages: write
    with:
      target: ${{ matrix.target }}
      registry: ghcr.io
      image: ${{ github.repository }}
