on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: joseprsm/nectarine/.github/workflows/.test.template.yml@main
    strategy:
      matrix:
        target: [ transform, train ]
        version: [ "3.10" ]
    with:
      target: ${{ matrix.target }}
      python_version: ${{ matrix.version }}

  build:
    uses: joseprsm/nectarine/.github/workflows/.build.template.yml@main
    needs: test
    permissions:
      packages: write
    with:
      registry: ghcr.io
      image: ${{ github.repository }}

  publish:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        version: [ "3.10" ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - run: |
        python -m pip install --upgrade pip
        pip install build
    - run: python -m build
    - uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
